# Generated by Django 5.2.8 on 2025-12-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_portada_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('permitir_descarga', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'albumes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('artista_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('sitio_web_url', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('cancion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=15, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=200, null=True)),
                ('tamano_archivo', models.BigIntegerField(blank=True, null=True)),
                ('num_reproducciones', models.IntegerField(blank=True, null=True)),
                ('permitir_descarga', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CancionesArtistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_participacion', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'canciones_artistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CancionesGeneros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'canciones_generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('genero_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('imagen_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_perfil_path', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('es_email_verificado', models.IntegerField(blank=True, default=0, null=True)),
                ('es_admin', models.IntegerField(blank=True, default=0, null=True)),
                ('cancion_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
