# Generated by Django 5.2.8 on 2025-12-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaccionesCanciones',
            fields=[
                ('reaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('cancion_id', models.IntegerField()),
                ('tipo', models.CharField(max_length=7)),
                ('fecha_reaccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reacciones_canciones',
                'managed': False,
            },
        ),
    ]
