# Generated by Django 5.2.8 on 2025-12-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0002_reaccionescanciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCancion',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_rating', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ratings_canciones',
                'managed': False,
            },
        ),
    ]
